### ISSUE TITLE
Disable check for function/class/path/folder/... is not working

### ISSUE THREAD

**Issue by VincentLanglet** [pepakriz/phpstan-exception-rules#104]
I use phpstan for both my src/ and test/ folder.
But I want to use this extension only for my src folder.

I was expecting solving the issue with
```
exceptionRules:
        methodWhitelist:
            PHPUnit\Framework\TestCase: '##'
```

But I still getting error in my tests files.
```
Missing @throws ... annotation
```

I create a PR with failing tests https://github.com/pepakriz/phpstan-exception-rules/pull/103 for the rule introduced by @marcospassos 

```
        public function testFoo(): void
	{
		throw new RuntimeException();
	}

        public function testFooBis(): void
	{
		$this->bar(); // throwing exceptions
	}
```
SHOULD NOT return an error by phpstan

Plus, I don't agree with the `Unused @throws RuntimeException annotation` error for whitelist method. If I whitelist the method, I don't expect error if I'm a good guy who annotate the function.

That's why I add my proposal to fix the tests in the PR

**Comment by pepakriz** [comment]
Thank you for your interest! I think the correct fix is like this: https://github.com/pepakriz/phpstan-exception-rules/pull/107 because reporting `Unused @throws RuntimeException annotation` is expected. Whitelisted methods should not contain any `@throws` annotation. Do you agree? cc @marcospassos

**Comment by VincentLanglet** [comment]
I depends.
For me `whitelist method` means `method ignored by this extension`.
For you `whitelist method` means `method which should not contains @throws annotation even if they throws one`.
Both points of view have their advantage and their defaults.

Both implementation solve my main issue so I'm ok with the two PR.

Maybe it's better to merge yours since it's a patch
