### ISSUE TITLE
bug when catching "uncheckedExceptions" 

### ISSUE THREAD

**Issue by zeleznypa** [pepakriz/phpstan-exception-rules#117]
When I have a method that throws one from "uncheckedExceptions" and in another method, I want to catch it, but the PhpStan return error:

```
Throwable is never thrown in the corresponding try block    
```

The code looks like this https://phpstan.org/r/b2825581-5f6d-4c01-b08d-4658d077e16d
But there is no way how to set up it on phpstan.org

**Comment by VincentLanglet** [comment]
I think this is a duplicate of https://github.com/pepakriz/phpstan-exception-rules/issues/116

**Comment by zeleznypa** [comment]
@VincentLanglet Yes :) Closing ticket.
