### ISSUE TITLE
Issue after phpstan upgrade (unused & missing at the same time)

### ISSUE THREAD

**Issue by jakubvojacek** [pepakriz/phpstan-exception-rules#134]
First of all, thank you for the amazing repo.

Everything was working smoothly until I upgraded to phpstan 0.12.33 (from 0.12.7) and exception-rules to 0.11.1 (from 0.10.1). After the upgrade I am getting both unused @throws warnings and missing warnings

```
 ------ ------------------------------------------------------------------------- 
  Line   App.php                                                                  
 ------ ------------------------------------------------------------------------- 
  21     Unused @throws App\ApiModule\Lib\DatabaseSelectionException annotation   
  29     Missing @throws App\ApiModule\Lib\DatabaseSelectionException annotation  
  39     Unused @throws App\ApiModule\Lib\AppUnknownException annotation          
  48     Missing @throws App\ApiModule\Lib\AppUnknownException annotation  
```

Any idea what it could be, please? Not sure how I could share a reproduction sample.

**Comment by pepakriz** [comment]
Hi, I think it has something to do with https://github.com/phpstan/phpstan-src/pull/196 in v0.12.24. Can you check it? Otherwise, we need a failing sample.

**Comment by jakubvojacek** [comment]
surprisingly, updating from 7.2 to 7.4 PHP helped, thank you anyway!
