### ISSUE TITLE
Handling of @inheritDoc and {@inheritDoc}

### ISSUE THREAD

**Issue by Stadly** [pepakriz/phpstan-exception-rules#21]
The annotations `@inheritDoc` and `{@inheritDoc}` are not handled correctly.

According to [phpDocumentor](https://docs.phpdoc.org/guides/inheritance.html):
> The inline tag `{@inheritDoc}` is used in a description to import the description of a parent element...
> ...
> **Important** Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
> 
> However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard `@inheritDoc` that will serve that purpose.

So we have that
- `{@inheritDoc}` only imports the description of the super-element (`@throws` annotations are *not* imported).
- `@inheritDoc` should be used when the element should inherit all its information from a super-element (`@throws` annotations are imported).

More information is available in the [proposed phpDoc standard](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#61-making-inheritance-explicit-using-the-inheritdoc-tag).

### Test case
```php
<?php

interface TestInterface {
    /** @throws RuntimeException. */
    public function foo(): void;
}

class TestA implements TestInterface {
    /** @inheritDoc */
    public function foo(): void {
        throw new RuntimeException();
    }
}

class TestB implements TestInterface {
    /** @inheritDoc */
    public function foo(): void {
    }
}

class TestC implements TestInterface {
    /** {@inheritDoc} */
    public function foo(): void {
        throw new RuntimeException();
    }
}

class TestD implements TestInterface {
    /** {@inheritDoc} */
    public function foo(): void {
    }
}
```

### Expected result
```
 ------ ---------------------------------------------
  Line   src\test.php
 ------ ---------------------------------------------
  17     Unused @throws RuntimeException annotation
  24     Missing @throws RuntimeException annotation
 ------ ---------------------------------------------
```

### Actual result
```
 ------ ---------------------------------------------
  Line   src\test.php
 ------ ---------------------------------------------
  11     Missing @throws RuntimeException annotation
  30     Unused @throws RuntimeException annotation
 ------ ---------------------------------------------
```

**Comment by roukmoute** [comment]
Already in discussion here: https://github.com/pepakriz/phpstan-exception-rules/issues/17

**Comment by Stadly** [comment]
Thanks, @roukmoute. I considered posting my issue as comment in https://github.com/pepakriz/phpstan-exception-rules/issues/17, but decided to open a new issue instead. The reason is that https://github.com/pepakriz/phpstan-exception-rules/issues/17 only focuses on `{@inheritDoc}`, and I found it difficult to really understand the issue raised there. (The title is "`{@inheritdoc}` is not used to detect exception annotation", and the issue opens with "I think `{@inheritdoc}` should be used to import exception annotation.", but my understanding is exactly the opposite: `{@inheritdoc}` _is_ currently used to detect exception annotation, but it should not be.)

**Comment by pepakriz** [comment]
You are right, the current behavior is not ideal and probably wrong. But implementation uses phpstan reflection classes. So if you want to change/improve support of `@inheritdoc` docblock, please create an issue in https://github.com/phpstan/phpstan

**Comment by Stadly** [comment]
I have now created an issue: https://github.com/phpstan/phpstan/issues/1332

**Comment by pepakriz** [comment]
So I think I can close this. Thank you
