### ISSUE TITLE
"ThrowsScope": Undefined offset

### ISSUE THREAD

**Issue by voku** [pepakriz/phpstan-exception-rules#64]
```Undefined offset: -1 in ..../vendor/composer/pepakriz/phpstan-exception-rules/src/Rules/ThrowsScope.php on line 96```

with v0.6.1

**Comment by pepakriz** [comment]
Can you provide some code, which leads to this error?

**Comment by pepakriz** [comment]
Check it again with v0.6.2, please. It should be fixed.

**Comment by voku** [comment]
:+1: yep, it's fixed with v0.6.2

Thanks for your work!
