### ISSUE TITLE
Combining @inheritDoc and @throws void

### ISSUE THREAD

**Issue by Stadly** [pepakriz/phpstan-exception-rules#92]
Combining `@inheritDoc` and `@throws void` doesn't work.

```
interface Foo
{
    /**
     * @throws RuntimeException
     */
    public function test(): void;
}


class Baz implements Foo
{
    /**
     * @inheritDoc
     * @throws void
     */
    public function test(): void
    {
    }
}
```

Erroneously gives the error `Unused @throws RuntimeException annotation`.

**Comment by pepakriz** [comment]
Sorry, but this feature must be implemented in phpstan itself. See: https://github.com/phpstan/phpstan/issues/2206
